### ISSUE TITLE
关于thinker_support.gradle的配置问题

### ISSUE THREAD

**Issue by wjbd** [ckrgithub/BuglyAndTinker#1]
enable = true
这个怎么动态在config里面控制呢？

**Comment by ckrgithub** [comment]
> enable = true
> 这个怎么动态在config里面控制呢？

今天tinker热修复检查更新失败，都下发不成功。config配置很简单，已改，但未测试

**Comment by ckrgithub** [comment]
> > enable = true
> > 这个怎么动态在config里面控制呢？
> 
> 今天tinker热修复检查更新失败，都下发不成功。config配置很简单，已改，但未测试

![image](https://user-images.githubusercontent.com/18225851/50735832-d3378d80-11ef-11e9-968f-6f03584a5711.png)

**Comment by wjbd** [comment]
感谢提醒，谢谢，我这边已经通过测试了
